theme: minima
title: Adopting artificial intelligence in government 
description: This page is a companion page for the article Adopting artificial intelligence in government a unified framework and review, written by Vincent Straub, Deborah Morgan, Jonathan Bright, and Helen Margetts.
