title: 'Adopting artificial intelligence in government: a unified framework and review' 
description: 'Website supporting the project Adopting artificial intelligence in government: a unified framework and review' 
toc: true
author: Public Policy Programme, Alan Turing Institute
baseurl: /ai-gov-framework
show_excerpts: true 

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
