title: Adopting artificial intelligence in government
description: 'Website supporting the project Adopting artificial intelligence in government: a unified framework and review' 
toc: true
    
show_excerpts: true 

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
